// 药物数据
const drugs = [
    "Abacavir",
    "Acarbose",
    "Acenocoumarol",
    "Acetamide",
    "Acetazolamide",
    "Acetylcysteine",
    "Aciclovir",
    "Acipimox",
    "Aclacinomycin",
    "Aclarubicin",
    "Acrivastine",
    "Adapalene",
    "Ademetionine",
    "Adenosine Triphosphate",
    "Adrenaline",
    "Aescine",
    "Albendazole",
    "Alendronate Sodium",
    "Alfacalcidol",
    "Alginic Sodium Diester",
    "Allopurinol",
    "Allylestrenol",
    "Almitrine and Raubasine",
    "Alprazolam",
    "Alprostadil",
    "Alteplase",
    "Altretamine",
    "Aluminium　Hydroxide",
    "Amantadine",
    "Ambroxol",
    "Amiloride",
    "Amino Acid",
    "Amino-polypeptide",
    "Aminocaproic Acid",
    "Aminoglutethimide",
    "Aminomethylbenzoic Acid",
    "Aminophenazone",
    "Aminophylline",
    "Amiodarone",
    "Amitriptyline",
    "Amlodipine",
    "Ammonium Chloride",
    "Amobarbital",
    "Amorolfine",
    "Amoxicillin",
    "Amoxicillin and Clavulanate Potassium",
    "Amoxicillin and Flucloxacillin",
    "Amoxicillin and Sulbactam",
    "Amphotericin B",
    "Ampicillin",
    "Ampicillin and Cloxacillin",
    "Ampicillin and Sulbactam",
    "Amrinone",
    "Amyl Nitrite",
    "Anastrozole",
    "Andiantai",
    "Anethol Trithione",
    "Anetholtri　Thione",
    "Aniracetam",
    "Anisodine Hydrobromide",
    "Antazolin",
    "Antipyrine and Caffeine Citrate",
    "Anubi-polypeotide",
    "Apomorphine",
    "Aprindine",
    "Aprotinin",
    "Arginine",
    "Arotinolol",
    "Arsenious acid",
    "Artemether",
    "Artesunate",
    "Asparaginase",
    "Aspirin",
    "Astemizole",
    "Atenolol",
    "Atracurium",
    "Atropine",
    "Auranofin",
    "Azathioprine",
    "Azelastine",
    "Azithromycin",
    "Azlocillin",
    "Aztreonam",
    "Bacillus Licheniformis",
    "Baclofen",
    "Bambuterol",
    "Barium Sulfate [Ⅰ,Ⅱ]",
    "Batilolum",
    "Batroxobin (Defibrase)",
    "Beclometasone Dipropionate",
    "Belladonna",
    "Bemegride",
    "Benazepril",
    "Bendazol",
    "Benorilate",
    "Benproperine",
    "Benzafibrate",
    "Benzalkonium　Chloride　and　Cetrimonium　Bromide",
    "Benzathine Benzylpenicillin",
    "Benzbromarone",
    "Benzoic Acid",
    "Benzoyl Peroxide",
    "Benzylpenicillin",
    "Berbamine",
    "Berberine",
    "Betahistine",
    "Betamethasone",
    "Betaxolol",
    "Bicalutamide",
    "Bicyclol",
    "Bifendate",
    "Bifidobacterium Viable",
    "Bifonazole",
    "Bismuth Aluminate",
    "Bismuth Potassium Citrate",
    "Bismuth Subgallate",
    "Bismuthi　Subnitratis",
    "Bisoprolol",
    "Bleomycin",
    "Boric Acid",
    "Bortezomib",
    "Brimonidine",
    "Brinzolamide",
    "Bromhexine",
    "Bromisoval and Procaine",
    "Bromocriptine",
    "Bucinnazine",
    "Budesonide",
    "Buflomedil",
    "Bumetanide",
    "Bupivacaine",
    "Buprenorphine",
    "Buspirone",
    "Busulfan",
    "Calamine",
    "Calcipotriol",
    "Calcitriol",
    "Calcium Acetate",
    "Calcium Carbonate",
    "Calcium Chloride",
    "Calcium Disodium Edetate",
    "Calcium Folinate",
    "Calcium Gluconate",
    "Calcium　Citrate",
    "Camphor",
    "Candesartan",
    "Cantharidine",
    "Capecitabine",
    "Captopril",
    "Carbachol",
    "Carbamazepine",
    "Carbidopa",
    "Carbocisteine",
    "Carbomer",
    "Carbon　Nanoparticles",
    "Carboplatin",
    "Carboprost Methylate",
    "Carboprost　Tromethamine",
    "Carboxymethylcellulose　Sodium　Lubricant",
    "Carmofur",
    "Carmustine",
    "Carteolol",
    "Carvedilol",
    "Cascara,Bismuth　Subnitrate　and　Magnesium　Carbonate",
    "Casein Hydrolysate",
    "Caspofungin",
    "Castor Oil",
    "Cefaclor",
    "Cefadroxil",
    "Cefalexin",
    "Cefathiamidine",
    "Cefazolin",
    "Cefdinir",
    "Cefditoren　Pivoxil",
    "Cefepime",
    "Cefetamet　Pivoxil",
    "Cefixime",
    "Cefmetazole",
    "Cefminox",
    "Cefodizime",
    "Cefonicid",
    "Cefoperazone",
    "Cefoperazone and Sulbactam",
    "Cefotiam",
    "Cefoxitin",
    "Cefpodoxime　Proxetil",
    "Cefprozil",
    "Cefradine",
    "Ceftazidime",
    "Ceftiaxone",
    "Ceftizoxime",
    "Cefuroxime",
    "Celecoxib",
    "Cetirizine",
    "Cetuximab",
    "Cetylpyridinium Chloride",
    "Chlorambucil",
    "Chloramphenicol",
    "Chlormethine",
    "Chlormezanone",
    "Chloroquine",
    "Chlorphenamine",
    "Chlorpromazine",
    "Chlorprothixene",
    "Chlorquinaldol/Promestriene",
    "Chlortetracycline Hydrochloride",
    "Chorionic Gonadotrophin",
    "Chymotrypsin",
    "Ciclopirox Olamine",
    "Ciclosporin",
    "Cidopirox   Olamine",
    "Cilazapril",
    "Ciluostazot",
    "Cimetidine",
    "Cinepazide",
    "Cinnarizine",
    "Ciprofloxacin",
    "Cisplatin",
    "Citalopram",
    "Citicoline",
    "Clarithromycin",
    "Clenbuterol",
    "Clindamycin",
    "Clindamycin　Phosphate",
    "Clobetasol Propionate",
    "Clodronate Disodium",
    "Clofazimine",
    "Clomifene",
    "Clomipramine",
    "Clonazepam",
    "Clonidine",
    "Clopidogrel",
    "Clorprenaline",
    "Clotrimazole",
    "Cloxacillin",
    "Clozapine",
    "Coal Tar",
    "Coated Aldehyde Oxystarch",
    "Cobamamide",
    "Codeine",
    "Coenzyme A",
    "Coenzyme Q10",
    "Colchicine",
    "Colistin",
    "Colloidal Bismuth Pectin",
    "Compound Ammonium Glycyrrhizinate",
    "Compound Azintamide",
    "Compound Borax",
    "Compound Carraghenates",
    "Compound Chlorhexidine",
    "Compound Chlorzoxazone",
    "Compound Diphenoxylate",
    "Compound Glycyrrhizin",
    "Compound Liquorice (Brown`s Mixture)",
    "Compound Methionine and Choline Bitartrate",
    "Compound Platycodon",
    "Compound Tropicamide",
    "Compound Zedoary Turmeric Oil",
    "Compound α-Keto Acid",
    "Compound　Benzoic　Acid",
    "Compound　Diastase",
    "Compound　Methoxyphenamine",
    "Corticotrophin",
    "Cortisone",
    "Crotamiton",
    "Cyclic Adenosine Monophosphate",
    "Cyclophosphamide",
    "Cydiodine",
    "Cyproheptadine",
    "Cystine",
    "Cytarabine",
    "Cytidine　Disodium　Triphosphate",
    "Cytochrome C",
    "DHA and EPA Ethylester",
    "Daclizumab",
    "Dactinomycin",
    "Dalteparin",
    "Danazol",
    "Dapsone",
    "Daunorubicin",
    "Decloxizine",
    "Deferoxamine",
    "Defibrase",
    "Dehydrocholic Acid",
    "Deslanoside",
    "Desloratadine",
    "Desmopressin",
    "Dexamethasone",
    "Dextran",
    "Dextromethorphan",
    "Diammonium Glycyrrhizinate",
    "Diazepam",
    "Dibasic　Sodium　Phosphate",
    "Diclifenac　Potassium",
    "Diclofenac Sodiu",
    "Diclofenamide",
    "Didanosine",
    "Diethylcarbamazine",
    "Diethylstilbestrol",
    "Difenidol",
    "Digestive　Enzyme",
    "Digoxin",
    "Dihydroartemisinin",
    "Dihydrocodeine",
    "Dihydroergotamine",
    "Dihydroxydibutylether",
    "Diltiazem",
    "Dimefline",
    "Dimenhydrinate",
    "Dimercaprol",
    "Dimercaptosuccinic Acid",
    "Dimethicone",
    "Diosmin",
    "Dioxopromethazine",
    "Diphenhydramine",
    "Dipivefrine",
    "Diprophylline",
    "Dipyridamole",
    "Disopyramide",
    "Dithranol",
    "Dobesilate",
    "Dobutamine",
    "Docetaxel",
    "Domperidone",
    "Donepezil",
    "Dopamine",
    "Doxapram",
    "Doxazosin",
    "Doxepin",
    "Doxifluridine",
    "Doxofylline",
    "Doxorubicin",
    "Doxycycline",
    "Dried Yeast",
    "Droperidol",
    "Dydrogesterone",
    "Ebastine",
    "Econazole",
    "Econazole and Triamcinolone Acetonide",
    "Edaravone",
    "Efavirdine",
    "Elcatonin",
    "Emedastine",
    "Emetine",
    "Enalapril",
    "Enema",
    "Enflurane",
    "Enoxacin",
    "Entacapone",
    "Entecavir",
    "Enteral Nutrition",
    "Eperisone",
    "Ephedrine",
    "Epirubicin",
    "Epristeride",
    "Ergometrine",
    "Ergotamine Caffeine",
    "Ertapenem",
    "Erythromycin",
    "Erythromycin Cydocarbonate",
    "Erythromycin Ethylsuccinate",
    "Erythromycin　Stearate",
    "Erythromyin　Estolate",
    "Erythropoietin",
    "Esmolol",
    "Esomeprazole",
    "Estazolam",
    "Estradiol",
    "Estradiol Benzoate",
    "Estradiol Valerate",
    "Estramustine",
    "Estriol",
    "Estrogens",
    "Etamsylate",
    "Ethacridine",
    "Ethambutol",
    "Ethinylestradiol",
    "Ethosuximide",
    "Etidronate Disodium",
    "Etimicin",
    "Etomidate",
    "Etoposide",
    "Exemestane",
    "Famciclovir",
    "Famotidine",
    "Fasudil",
    "Fat Emulsion",
    "Fat-soluble vitamin",
    "Felodipine",
    "Fenofibrate",
    "Fentanyl",
    "Ferrous Fumarate",
    "Ferrous Gluconate",
    "Ferrous Saccharose",
    "Ferrous Succinate",
    "Ferulate",
    "Fibrinogen",
    "Fibrin　Sealant",
    "Finasteride",
    "Flavoxate",
    "Fleroxacin",
    "Flucloxacillin",
    "Fluconazol",
    "Flucytosine",
    "Fludarabine",
    "Flufenamic Acid",
    "Flumazenil",
    "Fluocinonide",
    "Fluorescein Sodium",
    "Fluorometholone",
    "Fluorouracil",
    "Fluoxetine",
    "Flupentixol",
    "Flupentixol and Melitracen",
    "Fluphenazine",
    "Flurazepam",
    "Flutamide",
    "Fluticasone",
    "Fluvastatin",
    "Folic Acid",
    "Formestane",
    "Formoterol",
    "Formylmerphalan",
    "Foscarnet Sodium",
    "Fosfomycin",
    "Fosinopril",
    "Fotemustine",
    "Fructose",
    "Fructose Diphosphate sodium",
    "Ftibamzone",
    "Furazolidone",
    "Furosemide",
    "Fusidic Acid",
    "Gabexate",
    "Gadodiamide",
    "Gadopentetate Meglumine",
    "Galanthamine",
    "Ganciclovir",
    "Gastrodine",
    "Gatifloxacin",
    "Gefarnate",
    "Gefitinib",
    "Gemcitabine",
    "Gemfibrozil",
    "Gemifloxacin",
    "Gentamicin",
    "Gestrinone",
    "Glibenclamide",
    "Gliclazide",
    "Glimepiride",
    "Glipizide",
    "Gliquidone",
    "Globulin Antihemophilia [Ⅷ]",
    "Glucosamine",
    "Glucose",
    "Glucurolactone",
    "Glutamate",
    "Glutamine Acid Amide",
    "Glutamine Dipeptide",
    "Glutathione",
    "Glycerin and Sodium Chloride",
    "Glycerol",
    "Glycerol Fructose",
    "Glyforfin",
    "Goserelin",
    "Granisetron",
    "Granulocyte-Macrophage　Colony　Stimulating　Factor",
    "Granulocyte　Colony-Stimulating　Factor",
    "Halcinonide",
    "Halometasone",
    "Haloperidol",
    "Heparin",
    "Hepatocyte Growth-Promoting Factors",
    "Hetastarch",
    "Homoharringtonine",
    "Hoof Nail Polypeptide",
    "Human Normal Immunoglobulin",
    "Human Serum Albumin",
    "Human　Hepatitis　B　Immunoglobulin",
    "Huperzine A",
    "Hyaluronidase",
    "Hydrobenzole",
    "Hydrochlorothiazide",
    "Hydrocortisone",
    "Hydrogen Peroxide",
    "Hydrotalcite",
    "Hydroxycamptothecin",
    "Hydroxycarbamide",
    "Hydroxychloroquine",
    "Hydroxyprogesterone Caproate",
    "Hydroxyzine",
    "Ibuprofen",
    "Ichthammol",
    "Idoxuridine",
    "Ifosfamide",
    "Imidapril",
    "Imipenem",
    "Imipramine",
    "Imiquimod",
    "Indapamide",
    "Indinavir",
    "Indirubin",
    "Indocyanine Green",
    "Indometacin",
    "Indometacin and Furazolidone",
    "Indometacin and Glucosamine",
    "Influenza　Virus　Vaccine",
    "Inosine",
    "Insulin",
    "Interferon",
    "Iobitridol",
    "Iodinated Oil",
    "Iodine Tincture",
    "Iodine　Glycerol",
    "Iohexol",
    "Iopamidol",
    "Iopanoic Acid",
    "Iophendylate",
    "Iopromide",
    "Ioversol",
    "Ipratropium Bromide",
    "Irbesartan",
    "Irinotecan",
    "Iron Dextran",
    "Iron Sorbitex",
    "Isepamicin",
    "Isoflurane",
    "Isoniazid",
    "Isoprenaline",
    "Isosorbide Dinitrate",
    "Isosorbide Mononitrate",
    "Isotretinoin",
    "Itraconazole",
    "Kanamycin",
    "Ketamine",
    "Ketoconazole",
    "Ketorolac　Tromethamine",
    "Ketotifen",
    "L-门冬酰胺酶",
    "Labetalol",
    "Lacidipine",
    "Lactasin",
    "Lactobacillin",
    "Lactulose",
    "Lamivudine",
    "Lamotrigine",
    "Lansoprazole",
    "Latamoxef",
    "Latanoprost",
    "Leflunomide",
    "Lentinan",
    "Lercanidipine",
    "Letrozole",
    "Leuprorelin",
    "Levamisole",
    "Levobunolol",
    "Levobupivacaine",
    "Levocabastine",
    "Levocarnitine",
    "Levocetirizine",
    "Levodopa",
    "Levodopa and Benserazide",
    "Levofloxacin",
    "Levonorgestrel",
    "Levothyroxine",
    "Lidocaine",
    "Ligustrazine",
    "Lindane",
    "Liothyronine",
    "Lisinopril",
    "Lithium Carbonate",
    "Live Combined B.Subtilis and E.Faecium",
    "Liver Extract",
    "Lobaplatin",
    "Lobeline",
    "Lodoxamide",
    "Lomefloxacin",
    "Lomustine",
    "Loperamide",
    "Loratadine",
    "Lorazepam",
    "Lornoxicam",
    "Losartan Potassium",
    "Lovastatin",
    "Low Molecular Heparin",
    "Loxoprofen",
    "Lumbrokinase",
    "Magnesium　Sulfate",
    "Mannatide",
    "Mannitol",
    "Maprotiline",
    "Mebendazol",
    "Meclofenoxate",
    "Mecobalamin",
    "Medicinal Charcoal",
    "Medroxyprogesterone",
    "Megestrol",
    "Meglumine Adipiodone",
    "Meglumine Diatrizoate",
    "Meisoindigotin",
    "Meloxicam",
    "Melphalan",
    "Menadiol",
    "Menadione Sodium Bisulfite",
    "Menotropins",
    "Mercaptopurine",
    "Meropenem",
    "Mesalazine",
    "Mesna",
    "Metaraminol",
    "Metformin",
    "Methadone",
    "Methenamine",
    "Methotrexate",
    "Methoxsalen",
    "Methyldopa",
    "Methylphenidate",
    "Methylprednisolone",
    "Methyltestosterone",
    "Methylthioninium Chloride",
    "Metoclopramide",
    "Metoprolol",
    "Metronidazole",
    "Mexiletine",
    "Mezlocillin",
    "Miconazole",
    "Micronomycin",
    "Midazolam",
    "Midodrine",
    "Mifepristone",
    "Milrinone",
    "Minocycline",
    "Minoxidil",
    "Mirtazapine",
    "Misoprostol",
    "Mitomycin",
    "Mitoxantrone",
    "Mizolastine",
    "Mizoribine",
    "Moclobemide",
    "Mometasone Furoate",
    "Monosialotetrahexosylganglioside",
    "Montelukast",
    "Moracizine",
    "Morphine",
    "Morrhuate Sodium",
    "Mosapride",
    "Moxifloxacin",
    "Mucopolysaccharide　Polysulfate",
    "Mupirocin",
    "Mycophenolate Mofetil",
    "Myrtol　Standardized",
    "Nabumetone",
    "Nalorphine",
    "Nalorphine　Hydrobromide",
    "Naloxone",
    "Nandrolone Phenylpropionate",
    "Naphazoline",
    "Naproxen",
    "Nelfinavir",
    "Neomycin",
    "Neostigmine",
    "Netilmicin",
    "Nevirapine",
    "Nicardipine",
    "Nicergoline",
    "Nicotinamide",
    "Nicotinylmethylamide",
    "Nifedipine",
    "Nikethamide",
    "Nilestriol",
    "Nimesulide",
    "Nimodipine",
    "Nimustine",
    "Nitrazepam",
    "Nitrendipine",
    "Nitrocaphane",
    "Nitrofurantoin",
    "Nitroglycerin",
    "Noradrenaline Bitartrate",
    "Norcantharidin",
    "Norethisterone",
    "Norfloxacin",
    "Norvancomycin",
    "Nysfungin",
    "Ocimi Gratissimi Oil",
    "Octreotide",
    "Ofloxacin",
    "Olanzapine",
    "Omeprazole",
    "Ondansetron",
    "Ornidazole",
    "Ornithine and Aspartate",
    "Oryzanol",
    "Oseltamivir",
    "Otilonium　Bromide",
    "Oxacillin",
    "Oxaliplatin",
    "Oxazepam",
    "Oxcarbazepine",
    "Oxiracetam",
    "Oxybuprocaine",
    "Oxybutynin",
    "Oxycodone",
    "Oxymetazoline",
    "Oxytocin",
    "Ozagrcl",
    "Paclitaxel",
    "Pamidronate Disodium",
    "Pancreatic Kininogenase",
    "Pancreatin",
    "Pancuronium　Bromide",
    "Panipenem",
    "Pantoprazole",
    "Papaverine",
    "Paracetamol",
    "Paroxetine",
    "Pazufloxacin",
    "Pefloxacin",
    "Pemirolast Potassium",
    "Penciclovir",
    "Penehyclidine",
    "Penfluridol",
    "Penicillamine",
    "Pentoxifylline",
    "Pentoxyverine",
    "Pepsin",
    "Pergolide",
    "Perindopril",
    "Perphenazine",
    "Pethidine",
    "Phenformin",
    "Phenobarbital",
    "Phenolphthalein",
    "Phenoxybenzamine",
    "Phenoxymethylpenicillin Potassium",
    "Phentolamine",
    "Phenylephrine",
    "Phenylpropanol",
    "Phenytoin Sodium",
    "Pilocarpine",
    "Pinaverium Bromide",
    "Pioglitazone",
    "Pipecuronium Bromide",
    "Piperacillin",
    "Piperacillin and Sulbactam",
    "Piperacillin and Tazobactam",
    "Piperaquine",
    "Piperazine",
    "Pipotiazine",
    "Piracetam",
    "Pirarubicin",
    "Pirenoxine",
    "Piribedil",
    "Piroxicam",
    "Pituitrin",
    "Podophyllotoxin",
    "Policresulen",
    "Polyene Phosphatidyl Choline",
    "Polyethylene Glycol",
    "Polyinosinic-polycytidylic　Acid",
    "Polymyxin",
    "Poractant　Alfa",
    "Potassium Chloride",
    "Potassium Citrate",
    "Potassium Dehydroandrograpolide Succinate",
    "Potassium Magnesium Aspartate",
    "Potassium Permanganate",
    "Potassium Phosphates",
    "Povidone Iodine",
    "Pralidoxime Chloride",
    "Pralidoxime Iodide",
    "Pranoprofen",
    "Prasterone",
    "Pravastatin",
    "Praziquantel",
    "Prazonsin",
    "Prednisolone　Acetate",
    "Prednisone",
    "Primaquine",
    "Primidone",
    "Probenecid",
    "Probucol",
    "Procaine",
    "Procaine Benzylpenicillin",
    "Procaterol",
    "Progesterone",
    "Prolonium Iodide",
    "Promestriene",
    "Promethazine",
    "Propafenone",
    "Propofol",
    "Propranolol",
    "Propylthiouracil",
    "Prostat",
    "Protamine",
    "Protionamide",
    "Pyrantel Pamoate",
    "Pyrazinamide",
    "Pyridostigmine Bromide",
    "Pyrimethamine",
    "Pyritinol",
    "Quetiapine",
    "Quinidine",
    "Quinine",
    "Rabeprazole",
    "Raceanisodamine",
    "Raloxifene",
    "Ramipril",
    "Ranitidine",
    "Recombinant Human Epidermal Growth Factor",
    "Recombinant Human Interleukin-2",
    "Recombinant Human Somatropin",
    "Recombinant　Bovine　Basophilic　Fibroblast　Growth　Factor",
    "Recombinant　Human　Ad-p53　Injection",
    "Recombinant　Human　Coagulation　VII",
    "Recombinant　Human　Interleukin-11",
    "Remifentanil",
    "Reserpine",
    "Ribavirin",
    "Ribonucleic Acid",
    "Ribostamycin",
    "Rice Bran Sterol",
    "Rifampicin",
    "Rifandine",
    "Rifaximin",
    "Risperidone",
    "Ritodrine",
    "Ritonavir",
    "Rituximab",
    "Rivastigmine",
    "Rocuronium Bromide",
    "Ropivacaine",
    "Rosiglitazone",
    "Roxithromycin",
    "Rutin",
    "Salbutamol",
    "Salcatonin",
    "Salicylic Acid",
    "Salmeterol",
    "Saquinavir",
    "Sarpogrelate",
    "Scopolamine",
    "Secobarbital",
    "Selegiline",
    "Selenious Yeast",
    "Selenium Sulfide",
    "Semustine",
    "Sertraline",
    "Sevoflurane",
    "Silibinin",
    "Simvastatin",
    "Sirolimus",
    "Sisomicin",
    "Smectite",
    "Sodium Aminosalicylate",
    "Sodium Bicarbonate",
    "Sodium Chloride",
    "Sodium Cromoglicate",
    "Sodium Dimercaptopropane Sulfonate",
    "Sodium Dimercaptosuccinate",
    "Sodium Glycerophosphate",
    "Sodium Hyaluronate",
    "Sodium Lactate",
    "Sodium Nitrite",
    "Sodium Nitroprusside",
    "Sodium Stibogluconate",
    "Sodium Sulfacetamide",
    "Sodium Sulfate",
    "Sodium Thiosulfate",
    "Sodium Valproate",
    "Sodium　Glucuronic　Acid",
    "Sodium　Glycididazole",
    "Sodium　Ibandronate",
    "Somatostatin",
    "Sotalol",
    "Sparfloxacin",
    "Spectinomycin",
    "Spironolactone",
    "Stanozolol",
    "Stavudine",
    "Streptokinase",
    "Streptomycin",
    "Strophanthin K",
    "Succinylated Gelatin",
    "Sucralfate",
    "Sufentanyl",
    "Sukfadiazine Silver",
    "Sukfadiazine Zine",
    "Sulfadiazine",
    "Sulfamethoxazole",
    "Sulfamethoxazole-Trimethoprim",
    "Sulfasalazine",
    "Sulindac",
    "Sulpiride",
    "Suxamethonium Chloride",
    "Tacalcitol",
    "Tacrolimus",
    "Tamoxifen",
    "Tamsulosin",
    "Tanshinon",
    "Tegafur",
    "Tegaserod",
    "Teicoplanin",
    "Telmisartan",
    "Teniposide",
    "Teprenone",
    "Terazosin",
    "Terbutaline",
    "Testosterone Propionate",
    "Testosterone Undecanoate",
    "Tetracycline",
    "Thalidomide",
    "Theophylline",
    "Thiamazole",
    "Thiamphenicol",
    "Thioridazine",
    "Thiotepa",
    "Thrombin",
    "Thrombogen Complex [Ⅱ Ⅶ Ⅸ Ⅹ]",
    "Thymopentin",
    "Thymosin",
    "Thymosin　α1",
    "Thyroid",
    "Tianeptine",
    "Tiapride",
    "Tibolone",
    "Ticarcillin",
    "Ticarcillin and Clavulanate Potassium",
    "Ticlopidine",
    "Timolol",
    "Tinidazole",
    "Tioguanine",
    "Tiopronin",
    "Tirofiban",
    "Tobramycin",
    "Tolbutamide",
    "Tolterodine",
    "Tolynicate　and　Naphthylacetic　Acid",
    "Topiramate",
    "Topotecan",
    "Torasemide",
    "Toremifene",
    "Tramadol",
    "Tranexamic Acid",
    "Transfer Factor",
    "Trastuzumab",
    "Travoprost",
    "Trazodone",
    "Trepibutone",
    "Tretinoin",
    "Triamcinolone",
    "Triamterene",
    "Triazolam",
    "Trifluoperazine",
    "Trihexyphenidyl",
    "Trimebutine",
    "Trimetazidine",
    "Tripelennamine",
    "Triprolidine",
    "Tripterysium Glycosides",
    "Triptorelin",
    "Trolamine",
    "Tropicamide",
    "Tropisetron",
    "Troxerutin",
    "Ubenimex",
    "Ulinastatin",
    "Urapidil",
    "Urokinase",
    "Ursodeoxycholic Acid",
    "Valaciciovir",
    "Valpromide",
    "Valsartan",
    "Vancomycin",
    "Vasopressin Tannate",
    "Vatacoenayme",
    "Vecuronium Bromide",
    "Venlafaxine",
    "Verapamil",
    "Verteporfin",
    "Verticil",
    "Viaminati",
    "Vinblastine",
    "Vincristine",
    "Vindesine",
    "Vinorelbine",
    "Vitamin A",
    "Vitamin B1",
    "Vitamin B12",
    "Vitamin B2",
    "Vitamin B4",
    "Vitamin B6",
    "Vitamin C",
    "Vitamin D2",
    "Vitamin D3",
    "Vitamin E",
    "Vitamin E Nicotinate",
    "Vitamin K1",
    "Vitamin　A　and　D",
    "Voglibose",
    "Voriconazole",
    "Warfarin",
    "Xylometazoline",
    "Zafirlukast",
    "Zaleplon",
    "Zidovudine",
    "Zinc Gluconate",
    "Zinc Oxide",
    "Zinc Sulfate",
    "Zoledronic　Acid",
    "Zolpidem",
    "Zopiclone",
    "α-酮酸",
    "β-Carotene",
    "β-胡萝卜素",
    "丁丙诺啡",
    "丁咯地尔",
    "丁螺环酮",
    "丁酸氢化可的松",
    "丁香罗勒油",
    "七叶皂苷钠",
    "七氟烷",
    "万古霉素",
    "三乙醇胺",
    "三唑仑",
    "三尖杉酯碱",
    "三氟拉嗪",
    "三磷酸胞苷",
    "三磷酸腺苷",
    "丙卡特罗",
    "丙吡胺",
    "丙戊酰胺",
    "丙戊酸钠",
    "丙氨酰谷氨酰胺",
    "丙泊酚",
    "丙硫异烟胺",
    "丙硫氧嘧啶",
    "丙磺舒",
    "丙米嗪",
    "丙酸倍氯米松",
    "丙酸氟替卡松",
    "丙酸氯倍他索",
    "丙酸睾酮",
    "东莨菪碱",
    "丝裂霉素",
    "两性霉素B",
    "丹参酮",
    "乌司他丁",
    "乌拉地尔",
    "乌洛托品",
    "乌苯美司",
    "乐卡地平",
    "乙哌立松",
    "乙琥胺",
    "乙胺丁醇",
    "乙胺嗪",
    "乙胺嘧啶",
    "乙酰半胱氨酸",
    "乙酰唑胺",
    "乙酰胺",
    "乳果糖",
    "乳酶生",
    "乳酸菌素",
    "乳酸钠",
    "二巯丁二酸",
    "二巯丁二钠",
    "二巯丙磺钠",
    "二巯丙醇",
    "二氧丙嗪",
    "二甲双胍",
    "二甲弗林",
    "二甲硅油",
    "二硫化硒",
    "二羟丙茶碱",
    "二羟二丁基醚",
    "五氟利多",
    "亚叶酸钙",
    "亚甲蓝",
    "亚砷酸",
    "亚硝酸异戊酯",
    "亚硝酸钠",
    "亚硫酸氢钠甲萘醌",
    "亚胺培南",
    "亮丙瑞林",
    "人乙型肝炎免疫球蛋白",
    "人免疫球蛋白",
    "人血白蛋白",
    "他克莫司",
    "他卡西醇",
    "他莫昔芬",
    "伊曲康唑",
    "伊班膦酸钠",
    "伊立替康",
    "伏格列波糖",
    "伏立康唑",
    "伐昔洛韦",
    "伯氨喹",
    "低分子量肝素",
    "佐匹克隆",
    "依地酸钙钠",
    "依巴斯汀",
    "依托咪酯",
    "依托泊苷",
    "依托红霉素",
    "依替米星",
    "依沙吖啶",
    "依米丁",
    "依美斯汀",
    "依西美坦",
    "依诺沙星",
    "依达拉奉",
    "依那普利",
    "依降钙素",
    "依非韦伦",
    "促皮质素",
    "促肝细胞生长素",
    "倍他司汀",
    "倍他洛尔",
    "倍他米松",
    "克仑特罗",
    "克拉霉素",
    "克林霉素",
    "克林霉素磷酸酯",
    "克罗米通",
    "克霉唑",
    "六甲蜜胺",
    "兰索拉唑",
    "凝血因子VIIa",
    "凝血酶",
    "凝血酶原复合物",
    "利培酮",
    "利多卡因",
    "利妥昔单抗",
    "利巴韦林",
    "利托那韦",
    "利福定",
    "利福平",
    "利福昔明",
    "利血平",
    "别嘌醇",
    "制霉素",
    "前列地尔",
    "加兰他敏",
    "加替沙星",
    "加贝酯",
    "劳拉西泮",
    "包醛氧淀粉",
    "匹维溴铵",
    "十一酸睾酮",
    "华法林",
    "单唾液酸四己糖神经节苷脂钠盐",
    "单硝酸异山梨酯",
    "卡前列甲酯",
    "卡前列素氨丁三醇",
    "卡培他滨",
    "卡巴胆碱",
    "卡托普利",
    "卡替洛尔",
    "卡比多巴",
    "卡泊三醇",
    "卡泊芬净",
    "卡波姆",
    "卡维地洛",
    "卡莫司汀",
    "卡莫氟",
    "卡那霉素",
    "卡铂",
    "卡马西平",
    "卤米松",
    "厄他培南",
    "厄贝沙坦",
    "去乙酰毛花苷",
    "去氢胆酸",
    "去氧氟尿苷",
    "去氧肾上腺素",
    "去氨加压素",
    "去氯羟嗪",
    "去甲万古霉素",
    "去甲斑蝥素",
    "去甲肾上腺素",
    "去羟肌苷",
    "去铁胺",
    "双嘧达莫",
    "双歧杆菌活菌",
    "双氢可待因",
    "双氢青蒿素",
    "双氢麦角胺",
    "双氯芬酸钠",
    "双氯芬酸钾",
    "双氯非那胺",
    "双环醇",
    "双羟萘酸噻嘧啶",
    "可乐定",
    "可待因",
    "可的松",
    "右旋糖酐",
    "右旋糖酐铁",
    "右美沙芬",
    "叶酸",
    "司他夫定",
    "司可巴比妥",
    "司坦唑醇",
    "司帕沙星",
    "司来吉兰",
    "司莫司汀",
    "吉法酯",
    "吉米沙星",
    "吉西他滨",
    "吉非替尼",
    "吉非罗齐",
    "吗啡",
    "吗替麦考酚酯",
    "吗氯贝胺",
    "吡喹酮",
    "吡嗪酰胺",
    "吡嘧司特钾",
    "吡拉西坦",
    "吡柔比星",
    "吡格列酮",
    "吡硫醇",
    "吡罗昔康",
    "吡诺克辛",
    "吡贝地尔",
    "吲哚美辛",
    "吲哚菁绿",
    "吲达帕胺",
    "呋喃唑酮",
    "呋喃妥因",
    "呋塞米",
    "咪唑斯汀",
    "咪唑立宾",
    "咪喹莫特",
    "咪康唑",
    "咪达唑仑",
    "咪达普利",
    "哈西奈德",
    "哌唑嗪",
    "哌喹",
    "哌嗪",
    "哌库溴铵",
    "哌拉西林",
    "哌拉西林三唑巴坦",
    "哌拉西林舒巴坦",
    "哌替啶",
    "哌泊塞嗪",
    "哌甲酯",
    "唑吡坦",
    "唑来膦酸",
    "喷托维林",
    "喷昔洛韦",
    "喹硫平",
    "噻吗洛尔",
    "噻奈普汀",
    "噻氯匹定",
    "四环素",
    "地匹福林",
    "地塞米松",
    "地奥司明",
    "地尔硫",
    "地屈孕酮",
    "地巴唑",
    "地氯雷他定",
    "地芬尼多",
    "地芬诺酯",
    "地蒽酚",
    "地衣芽胞杆菌活菌制剂",
    "地西泮",
    "地高辛",
    "坎地沙坦酯",
    "坦洛新",
    "垂体后叶",
    "埃索美拉唑镁",
    "培哚普利",
    "培氟沙星",
    "培高利特",
    "塞替派",
    "塞来昔布",
    "复方氯己定",
    "复方溴丙胺太林铝镁",
    "复方甘草",
    "复方硼砂",
    "复方莪术油栓",
    "多塞平",
    "多奈哌齐",
    "多巴丝肼",
    "多巴胺",
    "多巴酚丁胺",
    "多柔比星",
    "多沙唑嗪",
    "多沙普仑",
    "多潘立酮",
    "多烯磷脂酰胆碱",
    "多烯酸乙酯",
    "多磺酸粘多糖",
    "多粘菌素B",
    "多索茶碱",
    "多西他赛",
    "多西环素",
    "多西紫杉醇",
    "大观霉素",
    "天麻素",
    "夫西地酸",
    "头孢丙烯",
    "头孢他啶",
    "头孢他美酯",
    "头孢克洛",
    "头孢克肟",
    "头孢吡肟",
    "头孢呋辛",
    "头孢哌酮",
    "头孢哌酮舒巴坦",
    "头孢唑林",
    "头孢唑肟",
    "头孢地尼",
    "头孢地秦",
    "头孢妥仑匹酯",
    "头孢尼西",
    "头孢拉定",
    "头孢曲松",
    "头孢替安",
    "头孢氨苄",
    "头孢泊肟酯",
    "头孢硫脒",
    "头孢米诺",
    "头孢美唑",
    "头孢羟氨苄",
    "头孢西丁",
    "奈替米星",
    "奈非那韦",
    "奈韦拉平",
    "奋乃静",
    "奎宁",
    "奎尼丁",
    "奥卡西平",
    "奥司他韦",
    "奥布卡因",
    "奥扎格雷",
    "奥拉西坦",
    "奥昔布宁",
    "奥曲肽",
    "奥替溴铵",
    "奥氮平",
    "奥沙利铂",
    "奥沙西泮",
    "奥硝唑",
    "奥美拉唑",
    "妥布霉素",
    "孕三烯酮",
    "孟鲁司特钠",
    "安他唑啉",
    "安息香酊",
    "富马酸亚铁",
    "对乙酰氨基酚",
    "对氨基水杨酸钠",
    "小檗碱",
    "小檗胺",
    "小诺米星",
    "尼卡地平",
    "尼可刹米",
    "尼尔雌醇",
    "尼美舒利",
    "尼群地平",
    "尼莫司汀",
    "尼莫地平",
    "尼麦角林",
    "尿促性素",
    "尿激酶",
    "山梨醇铁",
    "山莨菪碱",
    "川芎嗪",
    "左卡尼汀",
    "左卡巴斯汀",
    "左布比卡因",
    "左布诺洛尔",
    "左旋咪唑",
    "左旋多巴",
    "左氧氟沙星",
    "左炔诺孕酮",
    "左甲状腺素钠",
    "左西替利嗪",
    "巯嘌呤",
    "己烯雌酚",
    "己酮可可碱",
    "己酸羟孕酮",
    "巴曲酶",
    "巴氯芬",
    "布地奈德",
    "布林佐胺",
    "布桂嗪",
    "布比卡因",
    "布洛芬",
    "布美他尼",
    "帕尼培南",
    "帕珠沙星",
    "帕米膦酸二钠",
    "帕罗西汀",
    "干扰素",
    "干酵母",
    "平阳霉素",
    "庆大霉素",
    "开塞露",
    "异丙嗪",
    "异丙托溴铵",
    "异丙肾上腺素",
    "异帕米星",
    "异戊巴比妥",
    "异氟烷",
    "异烟肼",
    "异环磷酰胺",
    "异维A酸",
    "恩他卡朋",
    "恩替卡韦",
    "恩氟烷",
    "戈舍瑞林",
    "戊乙奎醚",
    "戊酸雌二醇",
    "扎来普隆",
    "扎鲁司特",
    "扑米酮",
    "托吡卡胺",
    "托吡酯",
    "托尼萘酸",
    "托拉塞米",
    "托烷司琼",
    "托特罗定",
    "托瑞米芬",
    "抑肽酶",
    "抗Tac单抗",
    "抗血友病球蛋白",
    "拉坦前列素",
    "拉氧头孢",
    "拉米夫定",
    "拉莫三嗪",
    "拉西地平",
    "拉贝洛尔",
    "拓扑替康",
    "放线菌素D",
    "文拉法辛",
    "斑蝥素",
    "新斯的明",
    "新霉素",
    "昂丹司琼",
    "普伐他汀",
    "普拉洛芬",
    "普拉睾酮",
    "普罗布考",
    "普罗帕酮",
    "普罗碘铵",
    "普罗雌烯",
    "普萘洛尔",
    "普适泰",
    "普鲁卡因",
    "普鲁卡因青霉素",
    "曲伏前列素",
    "曲克芦丁",
    "曲匹布通",
    "曲吡那敏",
    "曲唑酮",
    "曲妥珠单抗",
    "曲安奈德",
    "曲安西龙",
    "曲普利啶",
    "曲普瑞林",
    "曲美他嗪",
    "曲美布汀",
    "曲马多",
    "更昔洛韦",
    "替加氟",
    "替加色罗",
    "替勃龙",
    "替卡西林",
    "替卡西林钠克拉维酸钾",
    "替尼泊苷",
    "替普瑞酮",
    "替硝唑",
    "替米沙坦",
    "替罗非班",
    "替考拉宁",
    "木香铝镁",
    "来曲唑",
    "来氟米特",
    "林旦",
    "果糖",
    "果糖二磷酸钠",
    "枯草杆菌、肠球菌二联活菌",
    "枸橼酸钙",
    "枸橼酸钾",
    "枸橼酸铋钾",
    "柔红霉素",
    "柳氮磺吡啶",
    "标准桃金娘油",
    "核糖核酸",
    "核糖霉素",
    "核酪",
    "格列吡嗪",
    "格列喹酮",
    "格列本脲",
    "格列美脲",
    "格列齐特",
    "格拉司琼",
    "桂利嗪",
    "桂哌齐特",
    "樟柳碱",
    "樟脑",
    "次没食子酸铋",
    "次硝酸铋",
    "毒毛花苷K",
    "比卡鲁胺",
    "比索洛尔",
    "毛果芸香碱",
    "氟他胺",
    "氟伐他汀",
    "氟哌利多",
    "氟哌啶醇",
    "氟哌噻吨",
    "氟哌噻吨美利曲辛",
    "氟奋乃静",
    "氟尿嘧啶",
    "氟康唑",
    "氟氯西林",
    "氟甲松龙",
    "氟罗沙星",
    "氟胞嘧啶",
    "氟芬那酸",
    "氟西汀",
    "氟西泮",
    "氟轻松",
    "氟达拉滨",
    "氟马西尼",
    "氢化可的松",
    "氢氧化铝",
    "氢氯噻嗪",
    "氧化锌",
    "氧氟沙星",
    "氨丁三醇",
    "氨力农",
    "氨基己酸",
    "氨基比林",
    "氨基葡萄糖",
    "氨基酸",
    "氨曲南",
    "氨氯地平",
    "氨溴索",
    "氨甲环酸",
    "氨甲苯酸",
    "氨碘肽",
    "氨糖美辛",
    "氨肽素",
    "氨苄西林",
    "氨苄西林氯唑西林",
    "氨苄西林钠舒巴坦",
    "氨苯砜",
    "氨苯蝶啶",
    "氨茶碱",
    "氨鲁米特",
    "氮卓斯汀",
    "氮甲",
    "氮芥",
    "氯丙嗪",
    "氯丙那林",
    "氯化琥珀胆碱",
    "氯化钙",
    "氯化钠",
    "氯化钾",
    "氯化铵",
    "氯吡格雷",
    "氯唑沙宗",
    "氯唑西林",
    "氯喹",
    "氯喹那多-普罗雌烯",
    "氯普噻吨",
    "氯氮平",
    "氯沙坦钾",
    "氯法齐明",
    "氯硝西泮",
    "氯米帕明",
    "氯米芬",
    "氯美扎酮",
    "氯胺酮",
    "氯膦酸二钠",
    "氯苯那敏",
    "氯解磷定",
    "氯诺昔康",
    "氯雷他定",
    "氯霉素",
    "水杨酸",
    "水飞蓟宾",
    "沙丁胺醇",
    "沙利度胺",
    "沙奎那韦",
    "沙格雷酯",
    "沙美特罗",
    "法舒地尔",
    "法莫替丁",
    "泛影葡胺",
    "泛昔洛韦",
    "波替单抗",
    "泮库溴铵",
    "泮托拉唑",
    "泼尼松",
    "泼尼松龙",
    "洛伐他汀",
    "洛哌丁胺",
    "洛度沙胺",
    "洛索洛芬",
    "洛美沙星",
    "洛莫司汀",
    "洛贝林",
    "洛铂",
    "流行性感冒疫苗",
    "消化酶",
    "淀粉酶",
    "溴吡斯的明",
    "溴己新",
    "溴米因",
    "溴莫尼定",
    "溴隐亭",
    "炉甘石",
    "炔诺酮",
    "炔雌醇",
    "烟酰胺",
    "烟酸",
    "烯丙吗啡",
    "烯丙雌醇",
    "煤焦油",
    "熊去氧胆酸",
    "爱普列特",
    "特布他林",
    "特拉唑嗪",
    "猪肺磷脂",
    "环丙沙星",
    "环吡酮胺",
    "环孢素",
    "环戊硫酮",
    "环磷腺苷",
    "环磷酰胺",
    "环酯红霉素",
    "玻璃酸酶",
    "班布特罗",
    "琥乙红霉素",
    "琥珀酰明胶",
    "琥珀酸亚铁",
    "瑞芬太尼",
    "甘氨双唑钠",
    "甘油",
    "甘油果糖",
    "甘油氯化钠",
    "甘油磷酸钠",
    "甘磷酰芥",
    "甘草甜素",
    "甘草酸二铵",
    "甘草酸单铵",
    "甘铋镁",
    "甘露聚糖肽",
    "甘露醇",
    "生长抑素",
    "甲地孕酮",
    "甲基多巴",
    "甲巯咪唑",
    "甲异靛",
    "甲氧氯普胺",
    "甲氧沙林",
    "甲氧那明",
    "甲氨蝶呤",
    "甲氯芬酯",
    "甲泼尼龙",
    "甲状腺",
    "甲睾酮",
    "甲砜霉素",
    "甲硝唑",
    "甲羟孕酮",
    "甲苯咪唑",
    "甲苯磺丁脲",
    "甲萘氢醌",
    "甲钴胺",
    "白消安",
    "益康唑",
    "益康唑曲安奈德（曲安奈德益康唑）",
    "盐酸利托君",
    "盐酸表柔比星",
    "盖胃平",
    "石杉碱甲",
    "硒酵母",
    "硝卡芥",
    "硝普钠",
    "硝苯地平",
    "硝西泮",
    "硝酸异山梨酯",
    "硝酸甘油",
    "硫代硫酸钠",
    "硫利达嗪",
    "硫唑嘌呤",
    "硫必利",
    "硫普罗宁",
    "硫糖铝",
    "硫酸钠",
    "硫酸钡[I型，Ⅱ型]",
    "硫酸锌",
    "硫酸镁",
    "硫鸟嘌呤",
    "硬脂酸红霉素",
    "硼酸",
    "碘佛醇",
    "碘化油",
    "碘塞罗宁",
    "碘帕醇",
    "碘普罗胺",
    "碘比醇",
    "碘海醇",
    "碘甘油",
    "碘番酸",
    "碘苯酯",
    "碘苷",
    "碘解磷定",
    "碘酊",
    "碳酸氢钠",
    "碳酸钙",
    "碳酸锂",
    "磷酸氢钠",
    "磷酸氢钾",
    "磷霉素",
    "磺胺嘧啶",
    "磺胺嘧啶银",
    "磺胺嘧啶锌",
    "磺胺甲噁唑",
    "磺胺甲噁唑-甲氧苄啶",
    "磺胺醋酰钠",
    "福美坦",
    "福莫司汀",
    "福莫特罗",
    "福辛普利",
    "秋水仙碱",
    "穿琥宁",
    "米力农",
    "米多君",
    "米托蒽醌",
    "米格来宁",
    "米氮平",
    "米索前列醇",
    "米诺地尔",
    "米诺环素",
    "米非司酮",
    "粒细胞巨噬细胞集落刺激因子",
    "粒细胞集落刺激因子",
    "粘菌素",
    "精氨酸",
    "糜蛋白酶",
    "糠甾醇",
    "糠酸莫米松",
    "索他洛尔",
    "紫杉醇",
    "红细胞生成素",
    "红霉素",
    "纤维蛋白原",
    "纤维蛋白粘合剂",
    "纳洛酮",
    "纳米炭",
    "细胞色素C",
    "绒促性素",
    "维A酸",
    "维库溴铵",
    "维拉帕米",
    "维替泊芬",
    "维生素A",
    "维生素AD",
    "维生素B1",
    "维生素B12",
    "维生素B2",
    "维生素B4",
    "维生素B6",
    "维生素C",
    "维生素D2",
    "维生素D3",
    "维生素E",
    "维生素E烟酸酯",
    "维生素K1",
    "维胺酯",
    "维酶素",
    "缩宫素",
    "缬沙坦",
    "罂粟碱",
    "罗哌卡因",
    "罗库溴铵",
    "罗格列酮",
    "罗红霉素",
    "美司钠",
    "美托洛尔",
    "美沙拉嗪",
    "美沙酮",
    "美法仑",
    "美洛昔康",
    "美洛西林",
    "美罗培南",
    "美西律",
    "美辛唑酮",
    "羟乙基淀粉",
    "羟乙膦酸钠",
    "羟喜树碱",
    "羟嗪",
    "羟基脲",
    "羟氯喹",
    "羟甲唑啉",
    "羟甲烟胺",
    "羟考酮",
    "羟苄唑",
    "羟苯磺酸钙",
    "羧甲司坦",
    "羧甲基纤维素钠",
    "联苯双酯",
    "联苯苄唑",
    "聚乙二醇",
    "聚甲酚磺醛",
    "聚维酮碘",
    "聚肌胞",
    "肌苷",
    "肝浸膏",
    "肝素",
    "肠内营养剂",
    "肾上腺素",
    "胃蛋白酶",
    "胆影葡胺",
    "胞磷胆碱",
    "胰岛素",
    "胰激肽原酶",
    "胰酶",
    "胱氨酸",
    "胶体果胶铋",
    "胸腺五肽",
    "胸腺肽",
    "胸腺肽α1",
    "胺碘酮",
    "脂肪乳",
    "腺苷蛋氨酸",
    "腺苷钴胺",
    "膦甲酸钠",
    "舍曲林",
    "舒必利",
    "舒林酸",
    "舒芬太尼",
    "色甘酸钠",
    "艾司唑仑",
    "艾司洛尔",
    "芦丁",
    "芬太尼",
    "苄星青霉素",
    "苯丁酸氮芥",
    "苯丙哌林",
    "苯丙酸诺龙",
    "苯丙醇",
    "苯乙双胍",
    "苯唑西林",
    "苯妥英钠",
    "苯巴比妥",
    "苯扎贝特",
    "苯海拉明",
    "苯海索",
    "苯溴马隆",
    "苯甲酸",
    "苯甲酸雌二醇",
    "苯西卤铵",
    "茚地那韦",
    "茴三硫",
    "茴拉西坦",
    "茶碱",
    "茶苯海明",
    "荧光素钠",
    "药用炭",
    "莫匹罗星",
    "莫沙必利",
    "莫西沙星",
    "莫雷西嗪",
    "萘丁美酮",
    "萘普生",
    "萘甲唑啉",
    "萘甲唑林",
    "葡萄糖",
    "葡萄糖酸亚铁",
    "葡萄糖酸钙",
    "葡萄糖酸锌",
    "葡萄糖酸锑钠",
    "葡醛内酯",
    "葡醛酸钠",
    "蒙脱石",
    "蒿甲醚",
    "蓖麻油",
    "蔗糖铁",
    "藻酸双酯钠",
    "蚓激酶",
    "蛋氨酸胆碱",
    "螺内酯",
    "西吡氯铵",
    "西咪替丁",
    "西地碘",
    "西妥昔单抗",
    "西拉普利",
    "西替利嗪",
    "西洛他唑",
    "西索米星",
    "西罗莫司",
    "西酞普兰",
    "角菜酸酯",
    "诺氟沙星",
    "谷氨酰胺",
    "谷氨酸",
    "谷维素",
    "谷胱甘肽",
    "贝美格",
    "贝诺酯",
    "贝那普利",
    "赖诺普利",
    "赛庚啶",
    "赛洛唑啉",
    "蹄甲多肽",
    "转移因子",
    "辅酶A",
    "辅酶Q10",
    "辛伐他汀",
    "达肝素",
    "达那唑",
    "过氧化氢",
    "过氧苯甲酰",
    "透明质酸钠",
    "酚妥拉明",
    "酚磺乙胺",
    "酚苄明",
    "酚酞",
    "酞丁安",
    "酮康唑",
    "酮替芬",
    "醋硝香豆素",
    "醋酸钙",
    "重组人p53腺病毒",
    "重组人生长激素",
    "重组人白介素-11",
    "重组人白介素－2",
    "重组人表皮生长因子",
    "重组牛碱性成纤维细胞生长因子",
    "重酒石酸卡巴拉汀",
    "金刚烷胺",
    "金诺芬",
    "金霉素",
    "钆双胺",
    "钆喷酸葡胺",
    "铝碳酸镁",
    "铝酸铋",
    "铝镁加",
    "链激酶",
    "链霉素",
    "长春地辛",
    "长春新碱",
    "长春瑞宾",
    "长春碱",
    "门冬氨酸钾镁",
    "门冬氨酸鸟氨酸",
    "间羟胺",
    "阿仑膦酸钠",
    "阿伐斯汀",
    "阿克拉霉素",
    "阿卡波糖",
    "阿司匹林",
    "阿司咪唑",
    "阿嗪米特",
    "阿奇霉素",
    "阿巴卡韦",
    "阿扑吗啡",
    "阿托品",
    "阿昔洛韦",
    "阿昔莫司",
    "阿普唑仑",
    "阿普林定",
    "阿曲库铵",
    "阿替普酶",
    "阿替洛尔",
    "阿柔比星",
    "阿桔片",
    "阿法骨化醇",
    "阿洛西林",
    "阿米三嗪萝巴新片",
    "阿米替林",
    "阿米洛利",
    "阿糖胞苷",
    "阿罗洛尔",
    "阿苯达唑",
    "阿莫罗芬",
    "阿莫西林",
    "阿莫西林克拉维酸钾",
    "阿莫西林舒巴坦钠",
    "阿莫西林钠氟氯西林",
    "阿达帕林",
    "阿那曲唑",
    "阿魏酸",
    "降压灵",
    "降纤酶",
    "雌三醇",
    "雌二醇",
    "雌激素",
    "雌莫司汀",
    "雷公藤多苷",
    "雷尼替丁",
    "雷洛昔芬",
    "雷米普利",
    "雷贝拉唑",
    "青蒿琥酯",
    "青霉素G",
    "青霉素V钾",
    "青霉胺",
    "靛玉红",
    "非洛地平",
    "非诺贝特",
    "非那雄胺",
    "鞣酸加压素",
    "顺铂",
    "颠茄",
    "香菇多糖",
    "马普替林",
    "骨化三醇",
    "高锰酸钾",
    "鬼臼毒素",
    "鱼石脂",
    "鱼精蛋白",
    "鱼肝油酸钠",
    "鲑降钙素",
    "鲨肝醇",
    "麦角新碱",
    "麦角胺咖啡因",
    "麻黄碱",
    "黄体酮",
    "黄酮哌酯",
    "鼠李铋镁",
    "齐多夫定"
];

// 导出药物数据
module.exports = {
  drugs
};